### ISSUE TITLE
Create project Kanban board 

### ISSUE THREAD

**Issue by ShadyShawkat** [ShadyShawkat/React-Group-Project#21]
# Team members
- Shady Shawkat
- Will Teixeira

[Here is our kanban board](https://github.com/ShadyShawkat/React-Group-Project/projects/1)

**Comment by julie-ify** [comment]
## Hi @ShadyShawkat and @iwillteixeira, 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments below

- [x] Let's ensure that you have 17 tasks in total for a team of two and not 13 tasks as you have currently. Maybe you accidentally deleted some tasks meant for a team of two members. these are the missing tasks: 
 - [1pt] Create website header with empty nav - Setup (group task)
 - [1pt] Create app and install basic dependencies - Setup (group task)
 - [1pt] Create empty My profile - Setup (group task)
 - [1pt] Create basic structure for Rockets - Setup

- [x] Let's share the tasks equally and assign the group tasks to both of you.
- [x] Let's share the tasks accordingly whereby one person works on everything concerning `Rockets` and the other on everything concerning `Missions`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issues thread if something is not 100% clear.

**Comment by hiromataba** [comment]
## STATUS: APPROVED :tada:  :tada: :1st_place_medal: 
Hi :wave:  @team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
